# Your translations go here. To be used with the 'translate' liquid filter
# Example:
#   {{ 'hello_world' | translate }}
#

# hello_world:
#   en: Hello world !
#   fr: Bonjour le monde !

language:
  en: Language
  de: Sprog

log_in: 
  en: Log In
  de: Log Ind

sign_up:
  en: Sign Up 
  de: Tilmeld

testing_environment:
  en: Testing environment 
  de: Testmiljø

follow_us: 
  en: Follow us
  de: Følg os

all_rights_reserved: 
  en: All Rights Reserved
  de: Alle rettigheder forbeholdes

get_started_now: 
  en: Get started now
  de: Start nu

locales:
  en: en
  de: de